# will be added to docker group on docker hosts
docker_users:
  - tom

# Optional: enable or disable deploying it-tools
docker_deploy_it_tools: true

# host port  http://server:8080

docker_it_tools_port: "8080"
